### ISSUE TITLE
Installation difficulties 

### ISSUE THREAD

**Issue by fotaras-github** [BioMedIA/dhcp-structural-pipeline#20]
Dear developers,

We are having difficulties installing the package on our Linux server.

More specifically, we are running into compilation issues with VTK, where it seems downloads/tests during the VTK “make” are not working properly and it dies at around 40% complete (VTK cmake runs fine, btw). So far, workbench and ITK compile just fine. We have previously installed DRAWEM on its own, and VTK compiled fine…So we suspect that there is something wrong with this dhcp version and VTK.

Unfortunately, we cannot use docker on our cluster. Would it be possible to create a singularity image for us?

PS: I have also opened a topic on neurostars as well (https://neurostars.org/t/developing-hcp-structural-pipeline-installation/19796) about this. 

Many thanks in advance!

**Comment by jcupitt** [comment]
It's best not to cross-post questions, it makes extra work for people trying to support software.

I'll close this issue and answer on neurostars.
