### ISSUE TITLE
label volumes have non-integer values

### ISSUE THREAD

**Issue by whinds** [BioMedIA/dhcp-structural-pipeline#3]
The outputs called "drawem_all_labels" and "draweme_tissue_labels" are segmentation volumes with index labels as values indicating which voxel is which region. However, there are non-integer values around the borders with other regions. Should we simply round these values to the nearest integer?

**Comment by jcupitt** [comment]
Hello @whinds, that sounds like a bug. I suppose it's been resampled somewhere with something other than NN interpolation. I'll investigate.

As a short-term fix, yes, try rounding. You could well find bad labels being generated, unfortunately.

**Comment by jcupitt** [comment]
Ah! Thanks for the update, I'll close.
