### ISSUE TITLE
Unable to factor linear system

### ISSUE THREAD

**Issue by AdebayoBraimah** [BioMedIA/dhcp-structural-pipeline#4]
[subject1-session1.surface.log](https://github.com/BioMedIA/dhcp-structural-pipeline/files/2822938/subject1-session1.surface.log)
[subject1-session1.surface.err.txt](https://github.com/BioMedIA/dhcp-structural-pipeline/files/2822941/subject1-session1.surface.err.txt)

I am running the dHCP via docker.

Post-segmentation, the surface reconstruction stage runs into the error:

```
Generic Warning: In /usr/local/dhcp/1.1.0-a/build/VTK/Common/Core/vtkMath.cxx, line 548
Unable to factor linear system

Error: Could not find a closed intersection with finite cutting plane near segmentation boundary!
Traceback (most recent call last):
  File "/usr/local/dhcp/1.1.0-a/build/MIRTK/build/lib/tools/recon-neonatal-cortex", line 938, in <module>
    check=args.check)
.
.
.
Error: recon-neonatal-cortex command returned non-zero exit status 1
```
I have attached the log and error files for the segmentation.

I am unsure of how to proceed on this issue.

[subject1-session1.surface.log](https://github.com/BioMedIA/dhcp-structural-pipeline/files/2822472/subject1-session1.surface.log)

**Comment by Thea-Eddie-Amy** [comment]
Hi,

I met the same problem as you did. Have you solved it?
Look forward to your response. Thank you in advance!

Xinyi
