### ISSUE TITLE
Labels for ROI's

### ISSUE THREAD

**Issue by whinds** [BioMedIA/dhcp-structural-pipeline#5]
Is there a handy look up table for all of the "87" labels used in the segmentation of ROI's?

In the atlas folder I can only find the table for 9 tissue types (CSF, white, grey, etc.)

Thanks!

**Comment by mblesac** [comment]
I think the table you are looking for is this one: https://github.com/MIRTK/DrawEM/blob/master/label_names/all_labels.csv

**Comment by whinds** [comment]
Yes, that's the one. Thank you!
